# Generated by Django 3.2.6 on 2021-09-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.CharField(default='test', max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='demo', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=400),
        ),
    ]
