# Generated by Django 3.2.6 on 2021-09-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image1',
            field=models.ImageField(default='sunglasses-5.png', upload_to='ptimage'),
        ),
    ]
