# Generated by Django 3.2.6 on 2021-12-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_productmodels_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodels',
            name='image1',
            field=models.ImageField(blank=True, upload_to='ptimage'),
        ),
        migrations.AddField(
            model_name='productmodels',
            name='image2',
            field=models.ImageField(blank=True, upload_to='ptimage'),
        ),
        migrations.AddField(
            model_name='productmodels',
            name='image3',
            field=models.ImageField(blank=True, upload_to='ptimage'),
        ),
    ]
