# Generated by Django 3.2.6 on 2021-12-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20211209_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodels',
            name='description',
        ),
        migrations.AddField(
            model_name='productmodels',
            name='description_para',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AddField(
            model_name='productmodels',
            name='description_para1',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AddField(
            model_name='productmodels',
            name='description_para2',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AddField(
            model_name='productmodels',
            name='description_para3',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AddField(
            model_name='productmodels',
            name='description_para4',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='productmodels',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
