# Generated by Django 3.2.6 on 2021-12-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20211209_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodels',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
